const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
(async () => {
  const browser = await chromium.launch({headless:true, ...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH} : {})});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1000}});
    const errors=[]; page.on('pageerror', error => errors.push(error.message));
    await page.goto('http://127.0.0.1:8768');
    await page.waitForFunction(() => !document.querySelector('#project-select').disabled);
    await page.click('[data-view=security]');
    await page.selectOption('#finding-execution','1');
    await page.waitForFunction(() => document.querySelector('#finding-evidence').value.includes('CSP: ausente'));
    await page.fill('#finding-title','CSP ausente no laboratório');
    await page.fill('#finding-impact','Defesa adicional ausente.');
    await page.fill('#finding-remediation','Configurar política CSP.');
    await page.selectOption('#finding-severity','low');
    await page.selectOption('#finding-review','confirmed');
    await page.click('#finding-form [type=submit], #finding-form button.primary');
    await page.waitForFunction(() => document.querySelector('#findings-list').textContent.includes('confirmed'));
    const downloadPromise = page.waitForEvent('download'); await page.click('#report-link');
    const report = await downloadPromise;
    assert.match(report.suggestedFilename(), /projeto-1/);
    await page.fill('#project-name','Projeto navegador B');
    await page.click('#project-form button');
    await page.waitForFunction(() => document.querySelector('#project-select').value !== '1');
    const projectId = await page.locator('#project-select').inputValue();
    await page.waitForFunction(() => document.querySelector('#findings-list').textContent.includes('Nenhum achado'));
    assert.equal(await page.locator('#finding-execution option').count(),1);
    await page.click('[data-view=scope]');
    await page.fill('#scope-input','127.0.0.1'); await page.click('#scope-form button');
    await page.waitForFunction(() => document.querySelector('#scope-list').textContent.includes('127.0.0.1'));
    await page.selectOption('#project-select','1');
    await page.waitForFunction(() => document.querySelector('#scope-input').value === '');
    await page.selectOption('#project-select',projectId);
    await page.waitForFunction(() => document.querySelector('#scope-input').value === '127.0.0.1');
    await page.click('[data-view=chat]');
    await page.fill('#chat-input','teste rede'); await page.click('#chat-form [type=submit]');
    await page.waitForSelector('#confirm-modal:not(.hidden)');
    assert.equal(await page.locator('#project-select').isDisabled(),true);
    await page.click('#confirm-approve');
    await page.waitForFunction(() => !document.querySelector('#task-cancel').disabled);
    await page.click('#task-cancel');
    await page.waitForFunction(() => document.querySelector('#task-progress').textContent.includes('Cancelada'));
    await page.waitForFunction(() => !document.querySelector('#project-select').disabled);
    await page.click('[data-view=security]');
    await page.waitForFunction(() => document.querySelector('#finding-execution').textContent.includes('cancelada'));
    await page.screenshot({path:'/tmp/cyber-workspace-browser.png',fullPage:true});
    assert.deepEqual(errors,[]);
    console.log('Browser OK: projects, isolated scope/findings, report download, confirmed-task process cancellation, evidence and no JS errors.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode=1; });
